### PR TITLE
Fix Division by zero exception

### PR DESCRIPTION
**Pull request by LameuleFR**
This PR fix this specific issue that has appear with PHP 8.0.

https://github.com/PrestaShop/PrestaShop/issues/31008

### CODE REVIEW

**Comment by MatShir** [comment]
@lmeyer1 What do you think ?

**Review by matks — APPROVED** [review]
Looks good to me 👍 however I see the QA team was having difficulties reproducing the problem on https://github.com/PrestaShop/PrestaShop/issues/31008 so I suggest that this would be tested by a developer

**Comment by Robin-Fischer-PS** [comment]
Indeed, a QA by Dev would be nice on this one.

**Comment by LameuleFR** [comment]
@Robin-Fischer-PS 

I don't think this PR needs a full QA revision by dev as the error has been present since PS 1.6 and there is no change in logic within the code

When the error occurred on PHP versions lower than 8.0 the result was already 0. 
My commit only avoids the error, there is no real change.

I'm already using this fix on multiple big store and it work great without any regression.
Benjamin

**Review by boherm — APPROVED** [review]

**Comment by lmeyer1** [comment]
@MatShir I think that it is time to fix this bug. I already reported it in january. It is almost 10 months since now. Please push this PR through. Thank you

> however I see the QA team was having difficulties reproducing the problem on https://github.com/PrestaShop/PrestaShop/issues/31008

I have difficulties to understand the working of QA. Recognize a division by zero exception does not need a high level in math. 

Fix obvious bugs should not be an obstacle course (un parcours du combattant) as it unfortuately is with prestashop.

**Comment by Robin-Fischer-PS** [comment]
Hi again,

@LameuleFR "QA by Dev" does not necessarily mean we'll be spending hours on it so it should be merged pretty quickly once a dev starts working on the QA. We test almost every PR, to ensure the quality of the software. Even "simple" PR can introduce regression (even if I don't think that yours will, just by looking at your code, it should be fine).

@lmeyer1 The problem on the issue was not to "recognize a division by zero exception", but to reproduce this exception. There was apparently some confusion and misunderstanding on the issue as which PS and PHP version to use, it can happen... But it's far from being a general rule ;)

**Comment by boherm** [comment]
Merged, thanks for your contribution @LameuleFR! 😉

**Comment by lmeyer1** [comment]
Thank you everyone!

**Pull request merged**
