### PR TITLE
Fixed behavior when selecting a tab

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fixed behavior when selecting a tab
| Type?         | bug fix
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/PrestaShop/PrestaShop/issues/20861
| How to test?  | Cf @khouloudbelguith scenario in PrestaShop/PrestaShop#20861<br>Please check on 177, develop and 176.

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Comment by jolelievre** [comment]
@Progi1984 This is a fix for 177? Is it retrocompatible for previous versions?

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
@jolelievre I think the fix is retrocompatible. I will add a check for QA.

**Review by NeOMakinG — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 

I still have the bug on 177 (did not try on 176 and develop) : 

pr dashtrends 32 1

**Comment by Progi1984** [comment]
@Robin-Fischer-PS 
* I just installed the 1.7.7.x branch.
* I have the module `dashtrends` in `dev` branch
* I have the bug
* I checkout the branch `issue20861` from  module `dashtrends`
* The bug is fixed

**Comment by Robin-Fischer-PS** [comment]
Hi @Progi1984 :)

Indeed, it was a cache problem on my side. By using private browsing it's OK ! QA :heavy_check_mark: 

pr dashtrends 32 2

**Comment by Progi1984** [comment]
Thanks @Robin-Fischer-PS

**Pull request merged**
