### PR TITLE
Update dashtrends.js

### PR DESCRIPTION
**Pull request by sete391**
Fix for low values on conversion ratio.

### CODE REVIEW

**Comment by sete391** [comment]
@Progi1984 Are you going to merge it?

**Comment by Progi1984** [comment]
@sete391 needs to be approved by an another core team member and qa validated. Thanks

**Comment by NeOMakinG** [comment]
Could you fill a bit more the description for the QA so they understand what to test easier ?

**Comment by SD1982** [comment]
Hi @sete391 Could you provide us more infos or maybe a scenario to test your PR ? Thanks

**Comment by sete391** [comment]
Hi, you cant test it with very low conversion ratio value, ie. 0.01%. When show the chart and parse it as integer, the value is parsed to 0. The PR allows a decimal values as 0.01 or 2.45.

**Comment by Progi1984** [comment]
Ping @SD1982

**Comment by SimonGrn** [comment]
Hello,
where is this chart exactly ? What conversion ratio are we supposed to be looking at ?

**Comment by sarahdib** [comment]
Hello

Since we had no news from you, I'll close this Pull Request. Feel free to open another one if you can provide more details.

Thank you!

**Pull request closed without merging**
